function [centersFiltered] = filterCenters(centers, nLin, nCol, maxLin)

disp('filterCenters');
    ii = find( ((centers(1,:))>=-nCol/2) & ...
               ((centers(1,:))<= nCol/2) & ...
               ((centers(2,:))>=-nLin/2) & ...
               ((centers(2,:))<= maxLin) ) ;
    centersFiltered = centers(:,ii);
